#!/bin/bash
if [ "$1" == "low" ]
then
 amixer -q set Master 2dB+ unmute
 TEXT=$(amixer sget Master | tail -1 | cut -d' ' -f6 | sed 's/\(\[\|\]\)//g')
elif [ "$1" == "high" ]
then
 amixer -q set Master 2dB- unmute
 TEXT=$(amixer sget Master | tail -1 | cut -d' ' -f6 | sed 's/\(\[\|\]\)//g')
elif [ "$1" == "mute" ]
then
 amixer -q set Master toggle
 TEXT=$(amixer sget Master | tail -1 | cut -d' ' -f8 | sed 's/\(\[\|\]\)//g')
else
 echo "Usage volume [low | high | mute]\n"
fi

ID=$(cat ~/.config/dunst/.dunst_volume)
if [ $ID -gt "0" ]
then
 notify-send -p -r $ID -i $ICON "Volume: $TEXT" > ~/.config/dunst/.dunst_volume
else
 notify-send -p -i $ICON "Volume: $TEXT" >~/.config/dunst/.dunst_volume
fi
